### ISSUE TITLE
Include instructions to run example?

### ISSUE THREAD

**Issue by kylecordes** [dustingetz/reagent-json-editor#1]
This is a request to make the readme of the project include instructions to get the example up and running. Looking at it I think I will get there when I have a few minutes to tinker with it, but for something worth publishing as an example, it is hopefully also worth a few instructions to avoid the need for that tinkering.

(Here is how it looks from a one minute glance: that I need to publish the outer project to a local repository, then adjust the inner project (example helloworld) to look and find the outer project JAR in such a local repo.  I reach this tentative, one minute conclusion because I am told by the software that "Could not find artifact org.dgetz:reagent-json-editor:jar:0.1.0-SNAPSHOT in clojars (https://clojars.org/repo/)", from which I conclude that the outer project is not yet considered done enough to actually be published to clojars. )

**Comment by dustingetz** [comment]
Hey this project is toy quality and hasn't seen a commit in months. I never should have posted it to the mailing list, sorry.

**Comment by kylecordes** [comment]
Thanks for sharing the attempt, anyway :-)

I tried running it, using lein localrepo to do what I described above... then it fails because it depends on something called "refine", which is not in the published 2.0 version of your cljs-cursor lib. Looks like it might have been there in an earlier "version" of that version.

Anyway, I give up :-)
